# -*- coding: utf8 -*-

# ...
PREFIX_DECLARATION_TYPE_INTEGER   = "i"
PREFIX_DECLARATION_TYPE_REAL      = "r"
PREFIX_DECLARATION_TYPE_CHARACTER = "s"
PREFIX_DECLARATION_TYPE_LOGICAL   = "l"
# ...

# ...
PREFIX_CONTEXT_TYPE_LOCAL    = "l"
PREFIX_CONTEXT_TYPE_ARGUMENT = "a"
PREFIX_CONTEXT_TYPE_MODULE   = "m"
PREFIX_CONTEXT_TYPE_OBJECT   = "o"
PREFIX_CONTEXT_TYPE_GLOBAL   = "g"
# ...

# ...
FORTRAN_EXTENSIONS = ["f90", "F90"]
# ...

